version: '3'

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=express-docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    profiles:
      - in_docker
    container_name: express-docker
    build: .
    environment:
      - PORT=80
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=express-docker
    ports:
      - "3000:80"
#    healthcheck:
#      test: ["CMD", "curl", "http://localhost"]
#      timeout: 20s
#      retries: 5
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: